In [2]:
import pandas as pd
import numpy as np
import json
import os

In [30]:
# Need to modify absolute path
missing = pd.read_csv("D:\Courses\Pattern Recognition\WLASL\WLASL\data_download\scripts\missing.txt")

<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
C:\Users\Yaoga\AppData\Local\Temp\ipykernel_11416\1809448572.py:2: SyntaxWarning: invalid escape sequence '\C'
  missing = pd.read_csv("D:\Courses\Pattern Recognition\WLASL\WLASL\data_download\scripts\missing.txt")


In [32]:
# Need to modify absolute path
content = json.load(open(r'D:\Courses\Pattern Recognition\WLASL\WLASL\data_download\scripts\WLASL_v0.3.json'))
available_filenames = set(os.listdir(r'D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\videos'))

## Genearate gloss + frame_array dataset

In [43]:
matched_samples = []
for entry in content:
    instances = entry['instances']
    gloss = entry['gloss']

    for inst in instances:
        video_id = inst['video_id']
        if video_id + '.mp4' in available_filenames:
            # print(f"video_id = {video_id}")
            matched_samples.append([video_id, gloss])

with open('matched_samples.txt', 'w') as f:
    f.write("video_file\tgloss\n")
    for video_file, gloss in matched_samples:
        print(f"video = {video_file}, gloss = {gloss}")
        f.write(f"{video_file}\t{gloss}\n")

video = 69241, gloss = book
video = 07069, gloss = book
video = 07068, gloss = book
video = 07070, gloss = book
video = 07074, gloss = book
video = 69302, gloss = drink
video = 17710, gloss = drink
video = 65540, gloss = drink
video = 17711, gloss = drink
video = 17712, gloss = drink
video = 17713, gloss = drink
video = 17709, gloss = drink
video = 17720, gloss = drink
video = 17721, gloss = drink
video = 17722, gloss = drink
video = 17723, gloss = drink
video = 17724, gloss = drink
video = 12328, gloss = computer
video = 12312, gloss = computer
video = 12311, gloss = computer
video = 12313, gloss = computer
video = 12314, gloss = computer
video = 12315, gloss = computer
video = 12316, gloss = computer
video = 12317, gloss = computer
video = 12318, gloss = computer
video = 12319, gloss = computer
video = 12320, gloss = computer
video = 12326, gloss = computer
video = 12327, gloss = computer
video = 05728, gloss = before
video = 05729, gloss = before
video = 05730, gloss = before
video 

In [ ]:
# matched_samples = pd.read_csv(r"D:\Courses\Pattern Recognition\UB-CSE-555\dataset\matched_samples.txt", sep='\t')

dataset = []
base_path = r"D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix"

for video, gloss in matched_samples:
# for row in matched_samples.itertuples(index=False):
#     gloss = row.gloss
#     video = row.video_file
    file_path = os.path.join(base_path, f"{video}.npy")
    print(file_path)
    if os.path.exists(file_path):
        matrix = np.load(os.path.join(base_path, f"{video}.npy"))
        dataset.append([gloss, matrix])
       
np.save("D:/Courses/Pattern Recognition/UB-CSE-555/data_preprocess/dataset/dataset_all_new.npy", np.array(dataset, dtype=object))

D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\69241.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\07069.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\07068.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\07070.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\07074.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\69302.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17710.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\65540.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17711.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17712.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17713.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17709.npy
find!!
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17720.npy
find!!
D:\Courses\Pattern Recogn

In [ ]:
input_all = np.load("D:/Courses/Pattern Recognition/UB-CSE-555/data_preprocess/dataset/dataset_all_new.npy", allow_pickle=True)
input_all

array([['book',
        array([[ 0.62274814,  0.52962554, -0.22350124, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.6234125 ,  0.5298457 , -0.34936157, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.62372196,  0.5299276 , -0.30116788, ...,  0.        ,
                 0.        ,  0.        ],
               ...,
               [ 0.62610203,  0.5376872 , -0.30210397, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.6260681 ,  0.5376671 , -0.30204448, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.6260516 ,  0.5376636 , -0.31451195, ...,  0.        ,
                 0.        ,  0.        ]], dtype=float32)              ],
       ['book',
        array([[ 0.6561511 ,  0.5301736 , -0.35653242, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.65637344,  0.5297119 , -0.31059882, ...,  0.        ,
                 0.        ,  0

## Add paddings make the video array structure consistent

In [ ]:
dataset_padding = []
# First pass to find the maximum number of frames (T)
T_max = 0
# base_path = "./dataset/matrix"
base_path = r"D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix"

for video, _ in matched_samples:
    file_path = os.path.join(base_path, f"{video}.npy")
    if os.path.exists(file_path):
        matrix = np.load(file_path)
        if (T_max < matrix.shape[0]):
            print(file_path)
        T_max = max(T_max, matrix.shape[0])  # update max frame length

print(f"Maximum number of frames: {T_max}")

# Second pass: pad matrices to T_max
for video, gloss in matched_samples:
    file_path = os.path.join(base_path, f"{video}.npy")
    if os.path.exists(file_path):
        matrix = np.load(file_path)
        T, D = matrix.shape  # T: frames, D: features (200)
        
        # Pad with zeros if needed
        if T < T_max:
            pad_amount = T_max - T
            pad_matrix = np.zeros((pad_amount, D), dtype=np.float32)
            matrix = np.vstack([matrix, pad_matrix])  # [T_max, D]

        dataset_padding.append([gloss, matrix])

# Save as object array
np.save("D:/Courses/Pattern Recognition/UB-CSE-555/data_preprocess/dataset/dataset_all_padding_new.npy", np.array(dataset_padding, dtype=object))

D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\69241.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\07070.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17713.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\17709.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\05733.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\63232.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\57628.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\23806.npy
D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\03156.npy
Maximum number of frames: 233


In [53]:
# input_padding = np.load("D:/Courses/Pattern Recognition/UB-CSE-555/dataset/dataset_all_padding_new.npy", allow_pickle=True)
# input_padding

test = np.load(r"D:\Courses\Pattern Recognition\WLASL\WLASL\dataset\matrix\50851.npy", allow_pickle=True)
test

array([[ 0.66295534,  0.50064456, -0.5206027 , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.663265  ,  0.50073475, -0.44001204, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.6634321 ,  0.5007413 , -0.4406063 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.66481847,  0.5016141 , -0.2615263 , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.66486984,  0.50275815, -0.25861448, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)

## Compress npy to npz

In [ ]:
data_padding = np.load(r'D:/Courses/Pattern Recognition/UB-CSE-555/data_preprocess/dataset/dataset_all_padding_new.npy', allow_pickle=True)
data = np.load(r'D:/Courses/Pattern Recognition/UB-CSE-555/data_preprocess/dataset/dataset_all_new.npy', allow_pickle=True)

np.savez_compressed('dataset_all_padding_new.npz', data=data_padding)
np.savez_compressed('dataset_all_new.npz', data=data)

In [ ]:
base_path = r"D:/Courses/Pattern Recognition/UB-CSE-555/data_preprocess/dataset"
compress_data = np.load(os.path.join(base_path, "dataset_all_padding_new.npz"), allow_pickle=True)['data']


array([['book',
        array([[ 0.62274814,  0.52962554, -0.22350124, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.6234125 ,  0.5298457 , -0.34936157, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.62372196,  0.5299276 , -0.30116788, ...,  0.        ,
                 0.        ,  0.        ],
               ...,
               [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.        ,  0.        ,  0.        , ...,  0.        ,
                 0.        ,  0.        ]], dtype=float32)              ],
       ['book',
        array([[ 0.6561511 ,  0.5301736 , -0.35653242, ...,  0.        ,
                 0.        ,  0.        ],
               [ 0.65637344,  0.5297119 , -0.31059882, ...,  0.        ,
                 0.        ,  0